### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by mwg3** [Hertzole/gold-player#23]
Hi, thanks for really good movement script. But i have two problems
When my player want to jump
he hits the roof?
and when im trying crouch he's under the world...
Could you help me? Thanks a lot!

**Comment by Hertzole** [comment]
Hello!
I'm not interely sure what you mean. Do you think you could send me a project where you can reproduce this or record the problem? That way I can get a much easier understanding of what's going on. :)

**Comment by mwg3** [comment]
Project is really big cause he has a lot of objects. Ok i will try to explain my problem. When i press jump button my player doesn't want to jump? This looks like it's blocking in invisible wall. Really weird.

**Comment by mwg3** [comment]
Sure.
https://imgur.com/Hsjoapo
https://imgur.com/BAXglps
https://imgur.com/aEL7Ysk

**Comment by mwg3** [comment]
And player layer 
https://imgur.com/XrO6Y2O

**Comment by mwg3** [comment]
Others settings are default

**Comment by Hertzole** [comment]
In the first picture, I suspect that is the Ground Layer. You need to put every layer there you want to collide with EXCEPT for the player layer. So if your world is generally built up by objects with the Default, Floor, HitBox, etc layer, make sure to add those in the Ground Layer. But exclude the Character layer from that.
I hope that helps! :)

**Comment by Hertzole** [comment]
I also discovered a bug with the crouching (see #24) that might be related to your problem with the player being in the ground when crouching. I'll make sure to fix that ASAP and then I can help you patch it until the next release, which will take a while!

**Comment by Hertzole** [comment]
Sorry for the semi spam. Just wanted to let you know how to quickly patch the player controller in case you have problem with the crouching.

1. Open the PlayerMovement script (Hertzole/Gold Player/Scripts/Core/Modules/PlayerMovement)
2. Change line 256 from 
`m_CrouchCameraPosition = PlayerController.Camera.CameraHead.localPosition.y - m_CrouchHeight;` 
to
`m_CrouchCameraPosition = PlayerController.Camera.CameraHead.localPosition.y - (CharacterController.height - m_CrouchHeight);`
(Can also be seen [here](https://github.com/Hertzole/gold-player/commit/34a3cb1502756b68200efbfbf94ac20b15cc797c#diff-5082383a114db82ba3e2ba91d54e6844R256))

I hope things work out for you! If not, just ask away! :)

**Comment by mwg3** [comment]
Hi, thanks for help Hertzole! You're so helpful and i will add information about you in my project!
My problem was with rigidbody when "Use gravity" function was on.
But i have 2 others problem :/
Your script doesn't have a camera collider and that is problem for me :/
And secondly..how to add knockback functions when player got damage?

**Comment by Hertzole** [comment]
Hello!
Gold Player unfortunately does not support rigidbodies, so some funky behaviour could occur with that. Glad you figured that out! :)
I'm not sure what you mean with camera collider. Could you elaborate?
Currently there's no support for knockback, but I could probably add that in the next release. I will look into it. Meanwhile, you could try to make a seperate script to apply knockback, like the example I found [here](https://answers.unity.com/questions/242648/force-on-character-controller-knockback.html). I hope that helps! :)

**Comment by mwg3** [comment]
Maybe script like 'rb.AddForce(target.transform.forward * Distance, ForceMode.Impulse);' will work with ur player movement script?

**Comment by Hertzole** [comment]
Right now I doubt it will work. But I'll do my best to add a easy to use knockback system.

**Comment by mwg3** [comment]
Hi brother. I have one mistake and one sugestion. Bug with camera collision https://imgur.com/a/Ek2hJIl
And will be awesome if you add on this project Falling damage :)
Thanks a lot for good project!

**Comment by mwg3** [comment]
Thank you so much! You're the most helpful guy I've ever seen :-)

**Comment by Hertzole** [comment]
Thank you! I try my best! :D

I will close this issue now as it seems like it's been resolved. If you have anything else you want to bring up, just comment again or open a new issue.

Remember to keep an eye out for new updates that will (hopefully!) include knockback and other fixes! :)
