### ISSUE TITLE
Error when on any Unity Version earlier than 2019.3, and not using the new Input System. 

### ISSUE THREAD

**Issue by ruudschouten** [Hertzole/gold-player#30]
In the GoldPlayerTests class I get an error because the MovingPlatforms.Initialize() method always needs two parameters.

```CSHARP
#if ENABLE_INPUT_SYSTEM && UNITY_2019_3_OR_NEWER
            playerController.Movement.MovingPlatforms.Initialize(playerController, input);
#else
            playerController.Movement.MovingPlatforms.Initialize(playerController);
#endif
```
This could be fixed by adding `null` to the Initialize Call or add a default value to PlayerModule.Initialize().

**Comment by Hertzole** [comment]
Good catch, thanks! It has been fixed.
