### ISSUE TITLE
Having problems using the new input system with mouse input.

### ISSUE THREAD

**Issue by KrasnotR** [Hertzole/gold-player#31]
I'm trying to use the new unity input system, and it seems this project does support it, but without a Input Action setup example, it's a bit hard to know how to setup it.

I've figured out how to use the buttons, but I so far:
 - Created an action map called "Player"
 - Created a "Look" Action with the type being "Value" and control type "Vector 2"

The path that works best on the binding of the Look action is the "Delta [Mouse]", but I can only move the mouse when the mouse is not locked to the screen.

As a final note I haven't changed the default values in the Gold Player Controller.

**Comment by Hertzole** [comment]
I'll do my best to help you! 
Indeed you should be using "Delta [Mouse]" for mouse movement on the Look action. I also recommend adding a 'Scale Vector 2' processor to the mouse binding and setting the X and Y values to 0.1. Otherwise, the mouse will move crazy fast due to how the input system works.
Now you say you can only move the mouse when the mouse is not locked to the screen: can you elaborate a bit? It seems odd that you can only move the mouse when it's not locked.

And as a final note; when I get around to it, I'll add a section to the wiki here to guide you through setting up input.

**Comment by KrasnotR** [comment]
Hi! Thanks for the very fast answer.

It actually just doesn't move at all when the mouse is locked on the screen.
If i have the option "Should Lock Cursor" I'm quickly able to move the camera for about half a second before it just stops responding to my mouse input. In the case I don't have that option enabled or I press ESC in the editor while playing I'm fully able to move the camera until my cursor hits the edge of my screen.

**Comment by Hertzole** [comment]
Hmm... very odd. I just need to ask some other questions then to help narrow down the problem.

1. Was it from a fresh import of Gold Player?
2. Did you use the package version or the .unitypackage version?
3. What Unity editor version are you using? (The new input system is only supported in 2019.3+.)
4. Are you using the built-in 'Gold Player Input System' component or are you using a custom one?

**Comment by KrasnotR** [comment]
1. I tried using the new Universal RP (formerly known as LWRP), but even on just the standard 3D option this happens.
2. 1.4
3. Unity 2020.1.0a13.1443
4. The standard I think, I used the GameObject > 3D Object > Gold Player Controller

**Comment by KrasnotR** [comment]
Here's a demonstration of the problem: https://youtu.be/wYk1Z1KKfNQ

**Comment by Hertzole** [comment]
Hi
I made a project in 2020.1a15 with Universal RP to test but I can't replicate the issue. May I ask what OS you're using? Just in case there's some weird Unity thing with an editor.
Also, do you have the possibility to try and write your own simple mouse look to see if the problem persists? That way we could know if it's Gold Player or Unity.
And if all else fails, do you have the possibility to share the project so I could take a look at it on my machine?
I'm sorry for the troubles!

**Comment by KrasnotR** [comment]
I'm using linux with the distro being Kubuntu, so far I haven't had any problems with the unity editor, but who knows. I will just try to do a build and see if the problem still persists outside the editor.

**Comment by KrasnotR** [comment]
Alright, I just tested, it seems to be a Unity problem, in the build it works just fine, but on the editor it doesn't work very well, oh well, let's just hope they fix that problem, in the meantime I will just use the old system.
Sorry for bothering.

**Comment by Hertzole** [comment]
Good to know it was Unity messing with us. Not so good that the issue exists. As you said, let's hope they fix it! I highly recommend you report it using their bug reporter! 😃 
And thanks to this I've found new problems that need fixing so something good came out of it at least! 
I'll be closing the issue for now. If you have anything else to add, feel free to open it again.
