### ISSUE TITLE
How can I embed the code in my project so I can modify the code my self

### ISSUE THREAD

**Issue by FredericoGauz** [Hertzole/gold-player#38]
Sorry if it is a very simple question, I just started using Unity and would like to use your project as my (third) person controller. I really liked many of the functions you have here and would like to adapt it to what I want. (have a many acceleration speeds or try to allow it to jump while running).

Would it be hard to give me some instructions on how to proceed?

Thanks,

**Comment by Hertzole** [comment]
Hi there!
I won't give you instructions really how to turn it into a third-person controller as that isn't directly supported and I don't really know how to do that at the top of my head.
But to get the code into your project, go to the [Releases ](https://github.com/Hertzole/gold-player/releases) and you can download a Unity package that you can import into your project and you get all the source code that you can edit. :)

**Comment by FredericoGauz** [comment]
Ah I got it now, thank you! =)
