### ISSUE TITLE
Can't get the player controller to even start without an error...

### ISSUE THREAD

**Issue by HendawgPlayz** [Hertzole/gold-player#41]
When I hit play after bringing the package in my game and setting up a simple input system I get this console error:

"NullReferenceException: Object reference not set to an instance of an object
Hertzole.GoldPlayer.PlayerCamera.MouseHandler (System.Single deltaTime) (at Library/PackageCache/se.hertzole.gold-player@eef1158b7d/Runtime/Core/Modules/PlayerCamera.cs:254)
Hertzole.GoldPlayer.PlayerCamera.OnUpdate (System.Single deltaTime) (at Library/PackageCache/se.hertzole.gold-player@eef1158b7d/Runtime/Core/Modules/PlayerCamera.cs:233)
Hertzole.GoldPlayer.GoldPlayerController.Update () (at Library/PackageCache/se.hertzole.gold-player@eef1158b7d/Runtime/Core/GoldPlayerController.cs:127)
"

This is almost definitely me doing something wrong and not realizing it but I don't know how I could have already done something wrong when I haven't really touched this package at all. Thank you for the support and sorry for the trouble!

**Comment by Hertzole** [comment]
Hi! Thank you for your interest in Gold Player!

Before I'll investigate this, are you using the regular branch or the dev branch?

**Comment by HendawgPlayz** [comment]
I am using the regular branch. and yes I am using the new input system, thanks! Let me know what more information you need (:

**Comment by HendawgPlayz** [comment]
I'm so sorry to have taken up your time but something must have been wrong with my project files because I restarted the project and this controller works great! Thank you for providing such a powerful tool for free. I hope you know how much people appreciate work like this. Have a great day! I'll close the issue now.

**Comment by Hertzole** [comment]
Thank you for your kind words! I'm glad it got resolved! If there's anything else, just make a new issue and I'll help you. I hope you'll enjoy gold player! :)
